name: Threat Intelligence Pipeline CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: threat_intel
          POSTGRES_USER: ti_user
          POSTGRES_PASSWORD: ti_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov
        
    - name: Initialize database
      run: |
        psql -h localhost -U ti_user -d threat_intel -f infra/init_db.sql
      env:
        PGPASSWORD: ti_password
        
    - name: Run tests
      run: |
        pytest tests/ -v --cov=api --cov=workers --cov-report=xml
      env:
        DATABASE_URL: postgresql://ti_user:ti_password@localhost:5432/threat_intel
        REDIS_URL: redis://localhost:6379/0
        API_KEY: test-key-ci
        MOCK_ENRICH: true
        ENABLE_REAL_ENRICH: false
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        docker build -f Dockerfile.api -t ti-pipeline-api:latest .
        docker build -f Dockerfile.worker -t ti-pipeline-worker:latest .
        
    - name: Test Docker images
      run: |
        docker run --rm ti-pipeline-api:latest python -c "import sys; print('API image OK')"
        docker run --rm ti-pipeline-worker:latest python -c "import sys; print('Worker image OK')"
        
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Check for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install linting tools
      run: |
        pip install black flake8 mypy
        
    - name: Check code formatting with Black
      run: |
        black --check api/ workers/ scripts/ tests/
        
    - name: Lint with flake8
      run: |
        flake8 api/ workers/ scripts/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        
    - name: Type check with mypy
      run: |
        mypy api/ workers/ --ignore-missing-imports

  integration:
    runs-on: ubuntu-latest
    needs: [test, build]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Start services
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30
        
    - name: Run integration tests
      run: |
        python scripts/ingest_feed.py samples/sample_iocs.csv --format csv --feed ci_test
        sleep 10
        curl -f -H "Authorization: Bearer test-key" http://localhost:8000/stats
        curl -f -H "Authorization: Bearer test-key" "http://localhost:8000/search?q=malicious"
        
    - name: Stop services
      if: always()
      run: |
        docker-compose -f docker-compose.yml down
